################################################################################
#                             mkdocs_hooks                                      #
#                                                                              #
# MkDocs build hooks for skforecast-ai documentation.                          #
# This work by skforecast team is licensed under the Apache License 2.0        #
################################################################################

from __future__ import annotations

import logging


class _AutorefsCliDataFilter(logging.Filter):
    """
    Drop the spurious autorefs warning raised for the CLI ``DATA`` placeholder.

    The CLI API reference page (``api/cli.md``) is generated by ``mkdocs-typer2``.
    The usage synopsis of the optional-argument commands renders as
    ``skforecast-ai plan [OPTIONS][DATA]``. The adjacent ``[OPTIONS][DATA]`` is
    parsed by ``mkdocs-autorefs`` as a reference-style link targeting ``DATA``,
    which does not exist, producing a harmless "Could not find cross-reference
    target 'DATA'" warning. The placeholder cannot be reformatted through the
    plugin, so this filter suppresses only that specific message.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        message = record.getMessage()
        is_cli_data_warning = (
            "api/cli.md" in message
            and "Could not find cross-reference target 'DATA'" in message
        )
        return not is_cli_data_warning


_cli_data_filter = _AutorefsCliDataFilter()


def on_config(config, **kwargs):  # noqa: ANN001, ANN003, ARG001
    """
    Attach the autorefs CLI ``DATA`` warning filter during MkDocs configuration.

    Parameters
    ----------
    config : mkdocs.config.defaults.MkDocsConfig
        The MkDocs configuration object.
    **kwargs
        Additional keyword arguments passed by MkDocs.

    Returns
    -------
    config : mkdocs.config.defaults.MkDocsConfig
        The unchanged MkDocs configuration object.
    """
    autorefs_logger = logging.getLogger(
        "mkdocs.plugins.mkdocs_autorefs._internal.plugin"
    )
    autorefs_logger.addFilter(_cli_data_filter)

    # Belt and suspenders: also filter at the handler level so the message is
    # dropped regardless of the exact autorefs logger name across versions.
    for logger_name in ("", "mkdocs"):
        for handler in logging.getLogger(logger_name).handlers:
            handler.addFilter(_cli_data_filter)

    return config
